### ISSUE TITLE
how to disable input during validation?

### ISSUE THREAD

**Issue by goenning** [andreaswilli/react-verification-input#132]
As validation happens async, I would like to disable input/change until validation completes, but I couldn't find a way to disable input. Any suggestions?

**Comment by andreaswilli** [comment]
Since the component is just a normal input element behind the scenes, all you need to do is set the disabled attribute there:
```jsx
<VerificationInput inputProps={{ disabled: isValidating }} />
```
This will prevent editing of the value.

If you also want to apply styles to indicate the disabled state: This is currently not officially supported and could definitely be improved.

You might be able to style it using some fancy CSS selectors. E.g. something like this:
```css
input[disabled] ~ .character {
  color: gray;
}
```
But of course this relies on the internal structure of the component which is not ideal.

**Comment by andreaswilli** [comment]
#133 should also make this more clear
