### ISSUE TITLE
SMS autocomplete not working properly on safari iOS

### ISSUE THREAD

**Issue by anurbecirovic** [andreaswilli/react-verification-input#57]
Not sure if anyone addressed this issue but I have a problem with the Autocomplete on Safari. 
Steps to reproduce:
0. Open Safari on iPhone and enter credentials on the website.
1. Get an SMS code from the service 
2. Select the first input box
3. Click autofill
4. The field gets populated and breaks for no reason. 

Happening only on iPhones and Safari.

I also tried on Chrome the same thing and it works fine.
In my case, it doesn't do anything just returns me back to the login screen.

Thanks for the help.

**Comment by andreaswilli** [comment]
I just tested with Safari and Chrome on iOS 14.3 which both worked as expected.
So it looks like the problem is more specific.

To investigate I need more information:
- version of package, iOS, etc.
- exact setup (snippet or complete code example)
- are you doing/using something "unusual"?

**Comment by anurbecirovic** [comment]
Hello Andreas, thank you for reaching out. 

The package version is 2.0.4 and iOS 15.3.1. 
The code for Code input is: 

```
const CodeInput: FC<CodeInputProps> = ({ value, onChange }) => {
return (
      <VerificationInput
             value={value}
             onChange={onChange}
             placeholder=""
             classNames={codeStyles}
             validChars="[0-9]*"
             removeDefaultStyles
             autoFocus
       />
}
```

The action: 

```
 const onChangeValue = (value: string) => {
    setValue(ConfirmCodeField.Code, value);
   // -- I also tried without this part below
    if (value.length === 6) {
      onConfirmCode(value);
    }
   // --  still doesn't work for me
};
```
`const { code = '' } = useWatch<FormInputs>({ control });`

Usage: 

` <CodeInput onChange={onChangeValue} value={code} disabled={isLoading} />`

I'm using react-hook-form

The current flow is: Open Safari on iPhone > Login screen > Enter email > Receive SMS > Try autofill the CODE (screenshot below) > It redirects you back to the login screen, without any error message.

![IMG-bd076c1040276f53979ea74f767af01e-V](https://user-images.githubusercontent.com/24942592/160794975-10119437-0136-4580-8fd3-e8a1e51d06ae.jpg)

**Comment by andreaswilli** [comment]
Thanks for the information. I'll look into it.

**Comment by andreaswilli** [comment]
So far I wasn't able to reproduce the issue.

However, I noticed two things:
1. You are not setting `inputProps={{ autoComplete: "one-time-code" }}` on the component. [According to Apple](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element) this is required to enable autocomplete and I don't get the option to fill in codes without setting this attribute on the input. Is this maybe something that changed in iOS 15 (I can only test 14.3 atm) or do you have another explanation?
2. Your value of `validChars="[0-9]*"` allows the user to enter an arbitrary number of digits, which is probably not what you want. Use a value of `0-9` to allow only digits (and use the `length` prop to set a custom length if needed). Still I'm not sure if this is related to the problem since I didn't encounter any issues even when using your value.

I couldn't find any differences in behavior between Safari and Chrome, either.

Btw, what's the purpose of using `react-hook-form` for this? Seems to me like simply using React state would be way easier for this very simple form.

**Comment by mohamedomara0** [comment]
@anurbecirovic  Hello anurbecirovic if this issue is resolved with you or not ?

**Comment by anurbecirovic** [comment]
Hello @mohamedomara0. I tried but haven't had luck with it. I left this issue in the app since it wasn't big blocker.
